version: "3"
services:
  web:
    build:
      context: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - "8182:8080"   # host:container
    environment:
      - PORT=8080
